# Generated by Django 2.2.7 on 2021-04-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210413_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('adres', models.CharField(max_length=30)),
                ('rodzaj_wyksztalcenia', models.CharField(max_length=30)),
                ('staz', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='odpowiedznaogloszenie',
            name='dodatkowe_informacje',
        ),
        migrations.RemoveField(
            model_name='odpowiedznaogloszenie',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='odpowiedznaogloszenie',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='odpowiedznaogloszenie',
            name='rodzaj_wyksztalcenia',
        ),
        migrations.RemoveField(
            model_name='odpowiedznaogloszenie',
            name='staz',
        ),
        migrations.RemoveField(
            model_name='ogloszenie',
            name='dodatkowe_wymagania',
        ),
        migrations.AddField(
            model_name='odpowiedznaogloszenie',
            name='tytul',
            field=models.CharField(default='Opowiedz na ogloszenie', max_length=50),
        ),
        migrations.CreateModel(
            name='Wymaganie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('opis_wymagania', models.CharField(max_length=500)),
                ('ogloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Ogloszenie')),
            ],
        ),
        migrations.CreateModel(
            name='OdpowiedzNaWymaganie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpowiedz_opisowa', models.CharField(max_length=500)),
                ('wymaganie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Wymaganie')),
            ],
        ),
        migrations.AddField(
            model_name='odpowiedznaogloszenie',
            name='uzytkownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Uzytkownik'),
        ),
    ]
