# Generated by Django 2.2.7 on 2021-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210417_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='login',
            field=models.CharField(default='dsf', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='password',
            field=models.CharField(default='dfsdf', max_length=30),
            preserve_default=False,
        ),
    ]
