# Generated by Django 2.2.7 on 2021-05-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210508_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='login',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
