# Generated by Django 2.2.7 on 2021-05-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210508_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='rodzaj_wyksztalcenia',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='staz',
        ),
    ]
